spring.application.name=controlador_de_filme
spring.application.name=controlador_de_filme

# Configuração do Banco de Dados H2 em Memória
spring.datasource.url=jdbc:h2:mem:streamingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Atualização automática do Schema do Banco
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Mostrar SQL no console para auditoria interna
spring.jpa.show-sql=true